[package]
name = "wire"
version = "0.1.0"
edition = "2021"

[dependencies]
native-tls = "0.2.12"
reqwest = { version = "0.12.11", features = ["blocking", "json"] }
scribe = { git = "https://github.com/JTan2231/scribe.git" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.134"
